version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - npm i -g serverless
  pre_build:
    commands:
  build:
    commands:
      - STAGE=dev
      - |
        if [ "refs/heads/main" = $CODEBUILD_WEBHOOK_HEAD_REF ]; then
          STAGE=prod
        fi
      - echo Stage $STAGE
      - echo Deploy started on `date`
      - serverless deploy --stage $STAGE --verbose
  post_build:
    commands:
      - echo Deploy completed on `date`
      
